; Application specific constants

; Operation status enum
STATUS_UNKNOWN_ERROR	equ 00h
STATUS_ONGOING		equ 01h
STATUS_EXITED_NORMALLY	equ 02h	
STATUS_INVALID_CHAR	equ 03h
STATUS_OUTPUT_NO_MEMORY	equ 04h
STATUS_INVALID_HEX_CHAR	equ 0ffh

; Common character definitions
CHAR_TAB		equ 09h
CHAR_SPACE		equ 20h
CHAR_CR			equ 0dh
CHAR_NL			equ 0ah
CHAR_BRACKET_SQ_L	equ 5bh
CHAR_BRACKET_SQ_R	equ 5dh
CHAR_COMMA		equ 2ch

CHAR_ZERO		equ 30h
CHAR_ONE		equ 31h
CHAR_TWO		equ 32h
CHAR_THREE		equ 33h
CHAR_FOUR		equ 34h
CHAR_FIVE		equ 35h
CHAR_SIX		equ 36h
CHAR_SEVEN		equ 37h
CHAR_EIGHT		equ 38h
CHAR_NINE		equ 39h

CHAR_UPPER_A		equ 41h
CHAR_UPPER_B		equ 42h
CHAR_UPPER_C		equ 43h
CHAR_UPPER_D		equ 44h
CHAR_UPPER_E		equ 45h
CHAR_UPPER_F		equ 46h

CHAR_LOWER_A		equ 61h
CHAR_LOWER_B		equ 62h
CHAR_LOWER_C		equ 63h
CHAR_LOWER_D		equ 64h
CHAR_LOWER_E		equ 65h
CHAR_LOWER_F		equ 66h

; Idk
MULTILINE_CMT_START	equ 2f2ah ; /*
MULTILINE_CMT_END	equ 2a2fh ; */
SINGLELINE_CMT_START	equ 2f2fh ; //
SINGLELINE_CMT_END	equ 0a0dh ; \n
